// <auto-generated />
using System;
using ControleFinanceiroPessoal.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiroPessoal.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceiroContext))]
    partial class FinanceiroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiroPessoal.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Movimentacoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cartão de Crédito",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(210),
                            Tipo = 2,
                            Valor = 825.82m
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2022, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Curso C#",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(227),
                            Tipo = 2,
                            Valor = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Salário",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(229),
                            Tipo = 1,
                            Valor = 7000.00m
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mercado",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(230),
                            Tipo = 2,
                            Valor = 3000.00m
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Farmácia",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(232),
                            Tipo = 2,
                            Valor = 300.00m
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Combustível",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(233),
                            Tipo = 2,
                            Valor = 800.25m
                        },
                        new
                        {
                            Id = 7,
                            Data = new DateTime(2022, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Financiamento Carro",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(234),
                            Tipo = 2,
                            Valor = 900.00m
                        },
                        new
                        {
                            Id = 8,
                            Data = new DateTime(2022, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Financiamento Casa",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(236),
                            Tipo = 2,
                            Valor = 1200.00m
                        },
                        new
                        {
                            Id = 9,
                            Data = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Freelance Projeto XPTO",
                            Inclusao = new DateTime(2025, 9, 20, 16, 22, 38, 33, DateTimeKind.Local).AddTicks(237),
                            Tipo = 1,
                            Valor = 2500.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
